services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      # Allow community nodes & tool usage (needed for n8n-nodes-mcp)
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_COMMUNITY_PACKAGES_ALLOW_BUILTIN_MODULES=true
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      # Optional: basic auth to protect UI if you ever open it
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=please-change-me
    volumes:
      - n8n_data:/home/node/.n8n

  n8n-mcp:
    image: ghcr.io/czlonkowski/n8n-mcp:latest
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - MCP_MODE=http
      - LOG_LEVEL=info
      - DISABLE_CONSOLE_OUTPUT=false
      - N8N_API_URL=http://n8n:5678
      - N8N_API_KEY=cli-dev-token
      - PORT=3003
      - AUTH_TOKEN=mcp-dev-token
    depends_on:
      - n8n
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  n8n_data:
